first = float(input("First number: \n"))
second = float(input("Second number: \n"))
third = float(input("Third number: \n"))
mean = float((first + second + third) / 3)
print(f"The mean of the numbers {first}, {second} and {third} is: {mean}")